# catppuccin-latte

# some global theme specific variables
set $gtk-theme catppuccin-latte-blue-standard+default 
set $icon-theme catppuccin-latte-blue-standard+default
set $gui-font Roboto 11
set $term-font JetBrainsMono NF
set $gtk-color-scheme prefer-light
set $kvantum-theme catppuccin-latte-blue
set $background $HOME/.config/sway/generated_background.svg
set $cursor-theme phinger-cursors-dark
set $vscode-theme "Noctis Lux"

set $rosewater #dc8a78
set $flamingo #dd7878
set $pink #ea76cb
set $mauve #8839ef
set $red #d20f39
set $maroon #e64553
set $peach #fe640b
set $yellow #df8e1d
set $green #40a02b
set $teal #179299
set $sky #04a5e5
set $sapphire #209fb5
set $blue #1e66f5
set $lavender #7287fd
set $text #4c4f69
set $subtext1 #5c5f77
set $subtext0 #6c6f85
set $overlay2 #7c7f93
set $overlay1 #8c8fa1
set $overlay0 #9ca0b0
set $surface2 #acb0be
set $surface1 #bcc0cc
set $surface0 #ccd0da
set $base #eff1f5
set $mantle #e6e9ef
set $crust #dce0e8

# ANSI colors
set $color0 #5c5f77
set $color1 #d20f39
set $color3 #df8e1d
set $color5 #ea76cb
set $color6 #179299
set $color7 #acb0be
set $color8 #6c6f85
set $color9 #d20f39
set $color10 #40a02b
set $color11 #df8e1d
set $color12 #1e66f5
set $color13 #ea76cb

set $background-color $base
set $text-color $text
set $accent-color $peach

# target                 title     bg    text   indicator  border
client.focused           $lavender $base $text  $rosewater $lavender
client.focused_inactive  $overlay0 $base $text  $rosewater $overlay0
client.unfocused         $overlay0 $base $text  $rosewater $overlay0
client.urgent            $peach    $base $peach $overlay0  $peach
client.placeholder       $overlay0 $base $text  $overlay0  $overlay0
client.background        $base
