#!/usr/bin/env bash
# Generates ~/.config/waybar/colors.css from sway theme variables.
# Only colors.css is overwritten — style.css is seeded once by waybar.sh
# and left for the user to customize freely.
# Args: background-color text-color accent-color error-color warning-color
set -u

BACKGROUND_COLOR="$1"
TEXT_COLOR="$2"
ACCENT_COLOR="$3"
ERROR_COLOR="$4"
WARNING_COLOR="$5"

WAYBAR_USER_DIR="$HOME/.config/waybar"
mkdir -p "$WAYBAR_USER_DIR"

cat > "$WAYBAR_USER_DIR/colors.css" <<EOF
/* Auto-generated by generate-waybar-style.sh — changes will be overwritten on theme switch */
@define-color theme_base_color ${BACKGROUND_COLOR};
@define-color theme_text_color ${TEXT_COLOR};
@define-color theme_bg_color ${BACKGROUND_COLOR};
@define-color theme_selected_bg_color ${ACCENT_COLOR};
@define-color error_color ${ERROR_COLOR};
@define-color warning_color ${WARNING_COLOR};
@define-color background_color ${BACKGROUND_COLOR};
EOF
