exec_always {
  /usr/share/sway/scripts/enable-gtk-theme.sh "$gtk-theme"
  gsettings set org.gnome.desktop.interface icon-theme "$icon-theme"
  gsettings set org.gnome.desktop.interface color-scheme "$gtk-color-scheme"
  /usr/share/sway/scripts/enable-cursor-theme.sh "$cursor-theme"
  gsettings set org.gnome.desktop.interface font-name "$gui-font"
  gsettings set org.gnome.desktop.input-sources show-all-sources true
  gsettings set org.gnome.desktop.interface monospace-font-name "$term-font"
  /usr/share/sway/scripts/fontconfig.sh "monospace" "$term-font"
  /usr/share/sway/scripts/update-vscode-settings.sh "$term-font" "$vscode-theme"
  /usr/share/sway/scripts/update-zed-settings.sh "$term-font" "$vscode-theme"
  /usr/share/sway/scripts/generate-bg.sh "$accent-color" "$text-color" "$background-color"

  kvantummanager --set "$kvantum-theme"
}

