exec_always {
  $apply_gtk_theme
  $apply_icon_theme
  $apply_color_scheme
  $apply_cursor_theme
  $apply_gui_font
  $configure_input_sources
  $apply_monospace_font
  $configure_fontconfig
  $apply_vscode_settings
  $apply_zed_settings
  $generate_background
  $generate_waybar_style
  $apply_kvantum_theme
}
