# Atari Classic Theme for Sway
# Inspired by the Atari 2600 and wood-grain consoles

set $base #1e1e2e
set $mantle #181825
set $crust #11111b

# Palette Colors
set $wood #5D4037
set $orange #fab387
set $gold #FFB300
set $green #a6e3a1
set $blue #89b4fa
set $silver #9399b2
set $text #cdd6f4
set $subtext1 #bac2de
set $subtext0 #a6adc8

# ANSI colors
set $color0 #45475a
set $color1 #f38ba8
set $color3 #f9e2af
set $color5 #f5c2e7
set $color6 #94e2d5
set $color7 #bac2de
set $color8 #585b70
set $color9 #f38ba8
set $color10 #a6e3a1
set $color11 #f9e2af
set $color12 #89b4fa
set $color13 #f5c2e7

set $background-color $base
set $text-color $text
set $accent-color $orange

set $gtk-theme catppuccin-mocha-peach-standard+default
set $icon-theme Papirus-Dark
set $cursor-theme retrosmart-xcursor-white-color
set $gtk-color-scheme prefer-dark
set $kvantum-theme catppuccin-mocha-peach
set $vscode-theme "Noctis Obscuro"

# window decorations
# Property Name         Border   BG       Text    Indicator Child Border
client.focused          $accent-color $accent-color $background-color $orange $accent-color
client.focused_inactive $mantle $mantle $subtext0 $mantle $mantle

client.unfocused        $crust $crust $subtext1 $crust $crust
client.urgent           #f38ba8 #f38ba8 $background-color #f38ba8 #f38ba8
client.placeholder      $crust $crust $subtext1 $crust $crust
client.background       $background-color

# Font
set $gui-font Terminess Nerd Font 12
set $term-font Terminess Nerd Font Mono 12
