source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.3.0"

group :jekyll_plugins do
  gem 'jekyll-get-json', '~> 1.0'
  gem 'jekyll-webp', '~> 1.0'
  gem "jekyll-remote-theme", '~> 0.4.3'
end
