name: prepare
on:
  repository_dispatch:
    types: [rebuild_image]
  push:
  schedule:
    - cron: "0 1 * * *"
    
jobs:
  release:
    runs-on: manjaro
    steps:
      - 
        uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yaml
      - 
        name: checkout
        uses: actions/checkout@v2
        with:
          repository: boredland/iso-profiles
          token: "${{ secrets.GITHUB_TOKEN }}"
          ref: 'sway'
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
      - 
        name: build
        run: |
          rm -rf .chroots
          buildiso -p sway  -r ./.chroots
          FILE_PATH=$(find /var/cache/manjaro-tools/iso/community/sway -type f -name "*.iso" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
          cp -f ${FILE_PATH} .
          echo "RELEASE_FILE=$(basename $FILE_PATH)" >> $GITHUB_ENV
      - 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          release_name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
      - 
        id: upload_release 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_FILE }}
          asset_name: ${{ env.RELEASE_FILE }}
          asset_content_type: application/zip
    
    outputs:
      url: ${{ steps.upload_release.outputs.browser_download_url }}

  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        env:
          URL: ${{ needs.release.outputs.url }}
        run: |
          mkdir -p public/_includes
          echo ${URL} >public/_includes/url.href
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
          fqdn: manjaro-sway.download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}