name: build
on:
  schedule:
    - cron:  '30 2 * * 0'
  workflow_dispatch:
  repository_dispatch:
    types:
    - iso_profile_update
    - image_profile_update
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  MIRROR: https://opencolo.mm.fcix.net/manjaro

jobs:
  prepare-release:
    runs-on: ubuntu-22.04
    steps:
      - id: time
        uses: boredland/get-time-action@dbc808befb89eb33fee64f5f4abce4d2a5fa7cfd # tag=2.0.0
        with:
          format: 'YYYYMMDDHHmm'
      - id: receive
        uses: boredland/kernel-info@main
    outputs:
      release_tag: ${{ steps.time.outputs.time }}
      longterm: ${{ steps.receive.outputs.longterm-pkg }}
      stable: ${{ steps.receive.outputs.stable-pkg }}
  build-image:
    runs-on: ubuntu-22.04
    needs: [prepare-release]
    strategy:
      fail-fast: false
      matrix:
        branch: [stable, testing, unstable]
        device: [rpi4]
    steps:
      - name: import sway key
        run: gpg --keyserver keys.openpgp.org --receive-keys ${{ vars.GPG_KEYID }}
      - name: arm build
        uses: manjaro-contrib/action-buildarmimg@main
        with:
          device: rpi4
          edition: sway
          branch: ${{ matrix.branch }}
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
          arm-profiles-repo: https://github.com/manjaro-sway/arm-profiles.git
          overlay-repo: https://packages.manjaro-sway.download/${{ matrix.branch }}/aarch64/manjaro-sway.db
  build-iso:
    runs-on: ubuntu-22.04
    needs: [prepare-release]
    strategy:
      fail-fast: false
      matrix:
        branch: [stable, unstable]
        include:
          - branch: stable
            kernel: ${{ needs.prepare-release.outputs.longterm }}
          - branch: unstable
            kernel: ${{ needs.prepare-release.outputs.stable }}
    steps:
      - name: import sway key
        run: gpg --keyserver keys.openpgp.org --receive-keys ${{ vars.GPG_KEYID }}
      - name: x86_64 build
        uses: manjaro-contrib/action-buildiso@main
        with:
          iso-profiles-repo: https://github.com/Manjaro-Sway/iso-profiles
          edition: sway
          branch: ${{ matrix.branch }}
          scope: full
          kernel: ${{ matrix.kernel }}
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
          additional-trusted-gpg: ${{ vars.GPG_KEYID }}
          build-mirror: ${{ env.MIRROR }}
  trigger-mirror:
    runs-on: ubuntu-22.04
    needs: [build-iso, build-image]
    steps:
      - uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: manjaro-sway/manjaro-sway
          event-type: new_release
  rollback:
    runs-on: ubuntu-22.04
    needs: [build-iso, build-image, prepare-release]
    if: ${{ failure() || cancelled() }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: rollback
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          ASSET_COUNT=$(gh release view ${{ needs.prepare-release.outputs.release_tag }} --json "assets" --jq '.assets | length')
          if [ "$ASSET_COUNT" -gt "2" ]; then exit 0;fi
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
          git push --delete origin ${{ needs.prepare-release.outputs.release_tag }}
