name: iso_build
on:
  push:
  repository_dispatch:
    types: [rebuild_image]

env:
  EDITION: sway
  BRANCH: unstable

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - 
        name: checkout
        uses: actions/checkout@v2
        with:
          repository: boredland/iso-profiles
          token: "${{ secrets.GITHUB_TOKEN }}"
          ref: sway
          path: 'iso-profiles'
      - 
        id: cache
        uses: actions/cache@v2
        with:
          path: pkg-cache
          key: ${{ env.EDITION }}-${{ env.BRANCH }}
      -
        name: build_full
        run: |
          mkdir -p manjaro-tools pkg-cache iso
          docker run -v --rm --privileged \
          -e EDITION=$EDITION \
          -e BRANCH=$BRANCH \
          -v $PWD/pkg-cache:/var/cache/pacman/pkg/ \
          -v $PWD/iso-profiles:/builder/iso-profiles/ \
          -v $PWD/manjaro-tools:/var/lib/manjaro-tools/ \
          -v $PWD/iso:/var/cache/manjaro-tools/iso \
          -t boredland/manjaro-builder
          
          FILE_PATH=$(find ./iso -type f -name "*.iso" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
          cp $FILE_PATH .
          echo "RELEASE_FILE_FULL=$(basename FILE_PATH)" >> $GITHUB_ENV
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
      - 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          release_name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
      - 
        id: upload_full_release 
        uses: boredland/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_FILE_FULL }}
          asset_name: ${{ env.RELEASE_FILE_FULL }}
          asset_content_type: application/x-iso-image
      - 
        id: release_cleaner
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      url: ${{ steps.upload_full_release.outputs.browser_download_url }}

  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        env:
          URL: ${{ needs.release.outputs.url }}
        run: |
          mkdir -p public/_includes
          echo ${URL} >public/_includes/url.href
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
          fqdn: manjaro-sway.download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}