name: gh pages

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - build_pages

concurrency: 
  group: "pages-deployment"
  cancel-in-progress: true

jobs:
  pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
    - name: download default iso
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        LATEST_RELEASE=$(gh release list --limit 1 --exclude-drafts | sed -e 's/\s.*$//')
        gh release view ${LATEST_RELEASE} --json assets --jq '[.assets[]]' >docs/assets.json
        
        mkdir -p docs/manjaro-sway
        cat docs/assets.json | jq '.[].url' | xargs wget -q -P docs/manjaro-sway
        
        # unzip files
        for file in docs/manjaro-sway/*.iso.zip; do 
          zip -FF $file --out manjaro-full.zip && unzip manjaro-full.zip -d docs/manjaro-sway/
        done
        ## remove unzipped files
        rm -f docs/manjaro-sway/*.zip || echo ok
        rm -f docs/manjaro-sway/*.z01 || echo ok

        ## create release filelist
        (cd docs/manjaro-sway && ls -l *iso*) | \
          jq -s -R 'split("\n") | [.[] | select(length > 0) | split(" ") | [.[] | select(. == "" | not)] | { size: .[4] | tonumber, name: .[-1], url: "https://manjaro-sway.s3.fr-par.scw.cloud/\(.[-1])" }]' \
          > docs/release.json

        cat docs/release.json

        sudo apt-get update
        sudo apt-get install mktorrent

        mktorrent -v -a udp://tracker.opentrackr.org:1337 -l 21 \
          -n "manjaro-sway" -w https://manjaro-sway.s3.fr-par.scw.cloud/ \
          -o docs/manjaro-sway/manjaro-sway.torrent \
          docs/manjaro-sway
        
        ls -l docs/*
    - name: s3 prune
      uses: remyleone/scw-s3-action@ac8ffd44c45b626ccf50b1de5758cd1ed64ff925 # v0.0.2
      with:
        args: s3 rm s3://manjaro-sway/*
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_REGION: "fr-par"
    - name: s3 upload
      uses: remyleone/scw-s3-action@ac8ffd44c45b626ccf50b1de5758cd1ed64ff925 # v0.0.2
      with:
        args: s3 cp ./docs/manjaro-sway s3://manjaro-sway/ --recursive
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_REGION: "fr-par"
    - name: cleanup upload dir
      run: rm docs/manjaro-sway/*iso*
    - name: upload github pages
      uses: actions/upload-pages-artifact@253fd476ed429e83b7aae64a92a75b4ceb1a17cf # v1.0.7
      with:
        path: './docs'
    - name: deploy github pages
      id: deployment
      uses: actions/deploy-pages@20a4baa1095bad40ba7d6ca0d9abbc220b76603f # v1.2.3
